services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: baitdash
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
